import { SOURCE_LIST } from '../data/sources'
import { href } from '../hooks/useRoute'

export default function Sources() {
  return (
    <div className="page-main">
      <p className="eyebrow">Sources</p>
      <h1 className="title">Where every fact comes from</h1>
      <div className="notice">
        Every first-aid step and every fact in this app is hard-coded from the documents below. No text is
        generated by software or a model. In an emergency, go to a hospital.
      </div>
      {SOURCE_LIST.map((s) => (
        <div className="src" key={s.id}>
          <b>{s.title}</b>
          <p>
            {s.publisher} · {s.year}
          </p>
          <a href={s.url} target="_blank" rel="noopener noreferrer">
            {s.url}
          </a>
        </div>
      ))}
      <p className="body" style={{ marginTop: 24 }}>
        India bite and death figures (9.1 million bites, 5,726 deaths a year) are from the ICMR national survey.
        Emergency numbers 112, 108 and 104 are government services; 108 and 104 coverage varies by state.
      </p>
      <div className="actions">
        <a className="btn" href={href('/')}>
          Back to start
        </a>
      </div>
    </div>
  )
}
